
name: supersetfirebase
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_database: ^11.1.6
  cloud_firestore: ^5.5.1
  provider: ^6.1.2

  http: ^1.2.2
  audioplayers: ^6.0.1
  firebase_analytics: ^11.3.0 
  confetti: ^0.8.0
  flutter_tts: ^4.2.1
  equations: ^5.0.2
  translator: ^1.0.0
  flip_card: ^0.7.0
  number_to_words_english: ^2.0.2
  number_to_words: ^1.0.0
  animated_text_kit: ^4.2.2
  spelling_number: ^0.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Mathmingle/
    - assets/Mathmingle/audio/
    - assets/Mathmingle/homescreen/
    - assets/Mathmingle/matchGame/chapter1.json
    - assets/Mathmingle/matchGame/chapter2.json
    - assets/Mathmingle/matchGame/chapter3.json
    - assets/Mathmingle/matchGame/chapter4.json
    - assets/Mathmingle/matchGame/chapter5.json
    - assets/Mathequations/Background.png
    - assets/Mathequations/PartsOfEquation.png
    - assets/Mathoperations/home_screen.png
    - assets/Mathoperations/heading.png
    - assets/Mathoperations/background.png
    - assets/Mathoperations/home_screen_vertical.png
    - assets/Mathoperations/background_vertical.png
    - assets/Mathoperations/plus.png
    - assets/Mathoperations/orange.png
    - assets/Mathoperations/despicable-me-minions.gif
    - assets/Mathoperations/apple.png
    - assets/Mathoperations/egg.png
    - assets/Mathoperations/child.png

