// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
   apiKey: "AIzaSyDYC7_yReYQZJWTl1O9n3auL9pRCZQp4A4",
   authDomain: "fih-superset-dev.firebaseapp.com",
   projectId: "fih-superset-dev",
   storageBucket: "fih-superset-dev.firebasestorage.app",
   messagingSenderId: "1058242616848",
   appId: "1:1058242616848:web:7f407ce57f5ae4eafb3495",
   measurementId: "G-1MLYB5F9ZG"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnAReKuJP4j1D_i8IgyekWOjaON_jOx6Y',
    appId: '1:582477984848:android:14e00f23881d5beea28d55',
    messagingSenderId: '582477984848',
    projectId: 'op-games-e9bd1',
    storageBucket: 'op-games-e9bd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvzIzENyfWO9WpR9t6skClB9NNP44i59w',
    appId: '1:582477984848:ios:734fe39ee732a20ba28d55',
    messagingSenderId: '582477984848',
    projectId: 'op-games-e9bd1',
    storageBucket: 'op-games-e9bd1.firebasestorage.app',
    iosBundleId: 'com.example.opGames',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvzIzENyfWO9WpR9t6skClB9NNP44i59w',
    appId: '1:582477984848:ios:734fe39ee732a20ba28d55',
    messagingSenderId: '582477984848',
    projectId: 'op-games-e9bd1',
    storageBucket: 'op-games-e9bd1.firebasestorage.app',
    iosBundleId: 'com.example.opGames',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ5L4OQVulBKUNORoKDEgOdko5OMADQiY',
    appId: '1:582477984848:web:339fe4bacc7c2f93a28d55',
    messagingSenderId: '582477984848',
    projectId: 'op-games-e9bd1',
    authDomain: 'op-games-e9bd1.firebaseapp.com',
    storageBucket: 'op-games-e9bd1.firebasestorage.app',
    measurementId: 'G-TCHXNS2GH5',
  );
}
