// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
   apiKey: "AIzaSyDYC7_yReYQZJWTl1O9n3auL9pRCZQp4A4",
   authDomain: "fih-superset-dev.firebaseapp.com",
   projectId: "fih-superset-dev",
   storageBucket: "fih-superset-dev.firebasestorage.app",
   messagingSenderId: "1058242616848",
   appId: "1:1058242616848:web:7f407ce57f5ae4eafb3495",
   measurementId: "G-1MLYB5F9ZG"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhH0zMN7AhAo-b_iAn-glu0OUFWtyHqD4',
    appId: '1:305130774164:android:cf1b45bb0952d2d67b1e81',
    messagingSenderId: '305130774164',
    projectId: 'test-math-ddd87',
    storageBucket: 'test-math-ddd87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDO4npzuaOhM817P74CZKmY1RQ19DbzfI',
    appId: '1:305130774164:ios:1b0fb62819d79e217b1e81',
    messagingSenderId: '305130774164',
    projectId: 'test-math-ddd87',
    storageBucket: 'test-math-ddd87.firebasestorage.app',
    iosBundleId: 'com.example.math',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDO4npzuaOhM817P74CZKmY1RQ19DbzfI',
    appId: '1:305130774164:ios:1b0fb62819d79e217b1e81',
    messagingSenderId: '305130774164',
    projectId: 'test-math-ddd87',
    storageBucket: 'test-math-ddd87.firebasestorage.app',
    iosBundleId: 'com.example.math',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx8_WLepOXwadr3p1jS6t7_fUyviq12mY',
    appId: '1:305130774164:web:a7a5371626a09a957b1e81',
    messagingSenderId: '305130774164',
    projectId: 'test-math-ddd87',
    authDomain: 'test-math-ddd87.firebaseapp.com',
    storageBucket: 'test-math-ddd87.firebasestorage.app',
    measurementId: 'G-6QC30MYBNY',
  );

}